version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      deps:
        patterns: ["*"]
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/ckned"
    schedule:
      interval: "daily"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      backend-deps:
        patterns: ["*"]
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns: ["*"]
    labels:
      - "dependencies"
